### PR TITLE
Fixes #85 Improvements to session management (Breaking Change) 

### LINKED ISSUE #85: make submitSessionEnd identity parameter optional and look up the user identity.
```js
const user: IUserInfo = $ExceptionlessClient.config.defaultData["@user"];
          if (user) {
            $ExceptionlessClient.submitSessionEnd(user.identity);
          }
          
```

### PR DESCRIPTION
**Pull request by niemyjski**
This sync's changes over from https://github.com/exceptionless/Exceptionless.Net and ensures that you opt into heartbeats.

The breaking change is around heartbeats not being sent / configured when you call setUserIdentity.

I also synced the compiler options which we might want to up our bundle to ES2019 or ES2021 from ES2017. I noticed node is still targeting node 12 with CJS which the new default is ESM. I think we may want to bump this and break this too while we are at it.

### CODE REVIEW

File: packages/core/src/configuration/Configuration.ts [hunk 1]
```diff
@@ -477,7 +470,39 @@ export class Configuration {
...
+   */
+  public currentSessionIdentifier: string | null = null;
+
+  /**
+   *
+   * @param sendHeartbeats Controls whether heartbeat events are sent on an interval.
+   * @param heartbeatInterval The interval at which heartbeats are sent after the last sent event. The default is 1 minutes.
+   * @param useSessionIdManagement Allows you to manually control the session id. This is only recommended for single user desktop environments.
+   */
+  public useSessions(sendHeartbeats: boolean = true, heartbeatInterval: number = 60000, useSessionIdManagement: boolean = false) {
```
Comment (niemyjski) [inline packages/core/src/configuration/Configuration.ts:492]: @ejsmith I'm not sure about useSessionIdManagement, I guess this is the safe default since this can be used on node.

File: packages/core/src/configuration/Configuration.ts [hunk 2]
```diff
@@ -477,7 +470,39 @@ export class Configuration {
...
+  /**
+   * Gets or sets a value indicating whether to automatically send session start,
+   * session heartbeats and session end events.
+   */
+  public sessionsEnabled = false;
+
+  /**
+   * Internal property used to track the current session identifier.
+   */
+  public currentSessionIdentifier: string | null = null;
```
Comment (niemyjski) [inline packages/core/src/configuration/Configuration.ts:484]: This is internal in the .net client, no modifier for that in ts.

File: packages/browser/package.json [hunk 3]
```diff
@@ -45,7 +45,7 @@
     "testEnvironment": "jsdom"
   },
   "scripts": {
-    "build": "tsc -p tsconfig.json && esbuild src/index.ts --bundle --sourcemap --target=es2017 --format=esm --outfile=dist/index.bundle.js && esbuild src/index.ts --bundle --minify --sourcemap --target=es2019 --format=esm --outfile=dist/index.bundle.min.js",
```
Comment (ejsmith) [inline packages/browser/package.json:48]: Why did you downgrade this one from es2019 to es2017?

File: packages/browser/src/plugins/BrowserLifeCyclePlugin.ts [hunk 4]
```diff
@@ -17,12 +17,19 @@ export class BrowserLifeCyclePlugin implements IEventPlugin {
 
     this._client = context.client;
 
-    globalThis.addEventListener("beforeunload", () => void this._client?.suspend());
+    globalThis.addEventListener("beforeunload", () => {
+      if (this._client?.config.sessionsEnabled) {
+        void this._client?.submitSessionEnd();
+      }
+
+      void this._client?.suspend();
```
Comment (ejsmith) [inline packages/browser/src/plugins/BrowserLifeCyclePlugin.ts:25]: Is suspend what we want to do here? Wouldn't we want to flush the queue? Does suspend do that?

File: packages/core/src/configuration/Configuration.ts (hunk 2 above)
Comment (ejsmith) [reply packages/core/src/configuration/Configuration.ts:484]: I guess that's fine. Not sure what anyone would use this for.

File: packages/core/src/configuration/Configuration.ts (hunk 1 above)
Comment (ejsmith) [reply packages/core/src/configuration/Configuration.ts:492]: It seems fine.

**Review by ejsmith — APPROVED** [review]

**Comment by ejsmith** [comment]
I'm for us updating it to only support NodeJS versions that are still supported for NodeJS. For browsers, I don't think we should push it higher than we need for the features we are using. I don't want to support any versions of IE at this point.

File: packages/browser/package.json (hunk 3 above)
Comment (niemyjski) [reply packages/browser/package.json:48]: Because all the other ones were es2017. I'm going to upgrade all of these.

File: packages/browser/src/plugins/BrowserLifeCyclePlugin.ts (hunk 4 above)
Comment (niemyjski) [reply packages/browser/src/plugins/BrowserLifeCyclePlugin.ts:25]:
```
    await EventPluginManager.suspend(new PluginContext(this));
    const { queue } = this.config.services;
    await queue.suspend();
    await queue.process();
    this.suspendSettingsTimer();
```

It shuts everything down (all timers and intervals) and then submits events.
